version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - save_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

      - run:
          name: Run tests with coverage
          command: |
            coverage run -m unittest discover -s tests
            coverage report -m

      - store_artifacts:
          path: cover

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
